'use server'

import { createClient } from '@/lib/supabase/server'
import { invoiceSchema } from '@/schemas/invoice'
import { revalidatePath } from 'next/cache'

/**
 * Create an invoice from a delivered load with auto-populated data.
 * Sets load status to 'invoiced' after successful creation.
 */
export async function createInvoiceFromLoad(
  loadId: string
): Promise<{ id?: string; error?: string }> {
  const supabase = await createClient()

  // Fetch load - must be in 'delivered' status
  const { data: load, error: fetchError } = await supabase
    .from('loads')
    .select('id, org_id, broker_name, broker_email, rate_amount, fuel_surcharge, accessorial_charges, total_charges')
    .eq('id', loadId)
    .eq('status', 'delivered')
    .single()

  if (fetchError || !load) {
    return { error: 'Load not found or not in delivered status' }
  }

  const today = new Date()
  const dueDate = new Date()
  dueDate.setDate(dueDate.getDate() + 30)

  // Insert invoice - invoice_number auto-generated by database trigger
  const { data: invoice, error: insertError } = await supabase
    .from('invoices')
    .insert({
      org_id: load.org_id,
      load_id: load.id,
      bill_to_company: load.broker_name || '',
      bill_to_email: load.broker_email || null,
      amount: load.rate_amount || 0,
      fuel_surcharge: load.fuel_surcharge || 0,
      accessorials: load.accessorial_charges || 0,
      total: load.total_charges || 0,
      status: 'draft' as const,
      issued_date: today.toISOString().split('T')[0],
      due_date: dueDate.toISOString().split('T')[0],
    })
    .select('id')
    .single()

  if (insertError || !invoice) {
    return { error: insertError?.message ?? 'Failed to create invoice' }
  }

  // Update load status to 'invoiced'
  await supabase
    .from('loads')
    .update({ status: 'invoiced', updated_at: new Date().toISOString() })
    .eq('id', loadId)

  revalidatePath('/loads')
  revalidatePath('/invoices')
  return { id: invoice.id }
}

/**
 * Update an existing invoice's fields.
 * Recomputes total = amount + fuel_surcharge + accessorials.
 */
export async function updateInvoice(
  id: string,
  formData: FormData
): Promise<{ error?: string }> {
  const supabase = await createClient()

  // Parse form data
  const raw = {
    bill_to_company: formData.get('bill_to_company') as string,
    bill_to_email: formData.get('bill_to_email') as string,
    bill_to_address: formData.get('bill_to_address') as string,
    amount: formData.get('amount') as string,
    fuel_surcharge: formData.get('fuel_surcharge') as string,
    accessorials: formData.get('accessorials') as string,
    total: formData.get('total') as string,
    issued_date: formData.get('issued_date') as string,
    due_date: formData.get('due_date') as string,
    notes: formData.get('notes') as string,
    payment_method: formData.get('payment_method') as string,
  }

  const result = invoiceSchema.safeParse(raw)
  if (!result.success) {
    return { error: result.error.issues[0]?.message ?? 'Validation failed' }
  }

  const parsed = result.data
  // Recompute total
  const total = parsed.amount + (parsed.fuel_surcharge ?? 0) + (parsed.accessorials ?? 0)

  const { error } = await supabase
    .from('invoices')
    .update({
      bill_to_company: parsed.bill_to_company,
      bill_to_email: parsed.bill_to_email || null,
      bill_to_address: parsed.bill_to_address || null,
      amount: parsed.amount,
      fuel_surcharge: parsed.fuel_surcharge ?? 0,
      accessorials: parsed.accessorials ?? 0,
      total,
      issued_date: parsed.issued_date,
      due_date: parsed.due_date,
      notes: parsed.notes || null,
      payment_method: parsed.payment_method || null,
      updated_at: new Date().toISOString(),
    })
    .eq('id', id)

  if (error) {
    return { error: error.message }
  }

  revalidatePath('/invoices')
  revalidatePath(`/invoices/${id}`)
  return {}
}
