-- Phase 7: Compliance module tables
-- 6 tables: compliance_profiles, compliance_items, compliance_alerts,
-- driver_qualifications, inspections, ifta_records
-- All with RLS org isolation using (select public.org_id()) pattern

-- Carrier compliance profiles
create table public.compliance_profiles (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id),
  dot_number text,
  mc_number text,
  is_dot_regulated boolean default false,
  carrier_type text not null check (carrier_type in (
    'medical_transport', 'box_truck', 'hotshot',
    'straight_truck', 'class_8', 'mixed_fleet'
  )),
  operating_authority_status text default 'active',
  insurance_provider text,
  insurance_policy_number text,
  insurance_expiry date,
  ifta_license_number text,
  ifta_expiry date,
  ucr_registration_year integer,
  ucr_expiry date,
  drug_testing_consortium text,
  drug_testing_account_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Compliance items (individual trackable obligations)
create table public.compliance_items (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id),
  compliance_profile_id uuid not null references public.compliance_profiles(id),
  category text not null check (category in (
    'dot_inspection', 'insurance', 'ifta', 'ucr',
    'drug_testing', 'driver_qualification', 'vehicle_registration',
    'operating_authority', 'hazmat', 'medical_card',
    'cdl_renewal', 'annual_inspection', 'state_permit',
    'bod_filing', 'insurance_filing', 'custom'
  )),
  title text not null,
  description text,
  due_date date,
  completed_date date,
  status text default 'upcoming' check (status in (
    'upcoming', 'due_soon', 'overdue', 'completed', 'waived', 'not_applicable'
  )),
  assigned_to uuid,
  vehicle_id uuid references public.vehicles(id),
  driver_id uuid references public.drivers(id),
  document_urls text[],
  notes text,
  recurrence_rule text,
  recurrence_months integer,
  alert_days_before integer[] default '{90, 60, 30, 14, 7, 1}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Compliance alerts (generated by scanner)
create table public.compliance_alerts (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id),
  compliance_item_id uuid not null references public.compliance_items(id),
  alert_type text not null check (alert_type in (
    'approaching', 'due_soon', 'overdue', 'expired', 'completed'
  )),
  days_until_due integer,
  message text not null,
  acknowledged boolean default false,
  acknowledged_by uuid,
  acknowledged_at timestamptz,
  notification_sent boolean default false,
  created_at timestamptz default now()
);

-- Driver qualification files
create table public.driver_qualifications (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id),
  driver_id uuid not null references public.drivers(id),
  cdl_number text,
  cdl_state text,
  cdl_class text check (cdl_class in ('A', 'B', 'C', 'none')),
  cdl_expiry date,
  medical_card_expiry date,
  endorsements text[],
  restrictions text[],
  mvr_last_pulled date,
  mvr_status text,
  drug_test_last_date date,
  drug_test_result text,
  annual_review_date date,
  road_test_date date,
  application_date date,
  hire_date date,
  termination_date date,
  dq_file_complete boolean default false,
  missing_documents text[],
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Inspection records
create table public.inspections (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id),
  vehicle_id uuid not null references public.vehicles(id),
  inspection_type text not null check (inspection_type in (
    'annual_dot', 'pre_trip', 'post_trip', 'roadside',
    'state', 'customer_required', 'internal'
  )),
  inspector_name text,
  inspection_date date not null,
  expiry_date date,
  result text check (result in ('pass', 'fail', 'conditional')),
  defects_found text[],
  defects_corrected text[],
  document_urls text[],
  notes text,
  created_at timestamptz default now()
);

-- IFTA quarterly data
create table public.ifta_records (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id),
  vehicle_id uuid not null references public.vehicles(id),
  quarter text not null,
  jurisdiction text not null,
  miles_traveled numeric(10,1) default 0,
  gallons_purchased numeric(10,3) default 0,
  tax_rate numeric(8,6),
  tax_owed numeric(10,2),
  tax_paid numeric(10,2),
  net_tax numeric(10,2),
  source text default 'manual' check (source in ('manual', 'eld', 'gps', 'fuel_card')),
  created_at timestamptz default now()
);

-- RLS policies
alter table public.compliance_profiles enable row level security;
alter table public.compliance_items enable row level security;
alter table public.compliance_alerts enable row level security;
alter table public.driver_qualifications enable row level security;
alter table public.inspections enable row level security;
alter table public.ifta_records enable row level security;

create policy "org_isolation" on public.compliance_profiles
  for all using (org_id = (select public.org_id()));
create policy "org_isolation" on public.compliance_items
  for all using (org_id = (select public.org_id()));
create policy "org_isolation" on public.compliance_alerts
  for all using (org_id = (select public.org_id()));
create policy "org_isolation" on public.driver_qualifications
  for all using (org_id = (select public.org_id()));
create policy "org_isolation" on public.inspections
  for all using (org_id = (select public.org_id()));
create policy "org_isolation" on public.ifta_records
  for all using (org_id = (select public.org_id()));

-- Indexes
create index idx_compliance_items_org_status on public.compliance_items(org_id, status);
create index idx_compliance_items_due_date on public.compliance_items(due_date);
create index idx_compliance_alerts_org_ack on public.compliance_alerts(org_id, acknowledged);
create index idx_driver_qualifications_org_driver on public.driver_qualifications(org_id, driver_id);
create index idx_inspections_org_vehicle on public.inspections(org_id, vehicle_id);
create index idx_ifta_records_org_vehicle_quarter on public.ifta_records(org_id, vehicle_id, quarter);
